### ISSUE TITLE
Sickbeard broke after OS update

### ISSUE THREAD

**Issue by jappish84** [VeNoMouS/Sick-Beard#20]
Hi, I updated my system to the latest OSMC running on raspberry pi and noticed that Sickbeard stopped working. All I get is this error message: 

`osmc@Trdck:~$ python SickBeard/SickBeard.py 
Starting up Sick Beard torrentProviders
Traceback (most recent call last):
  File "SickBeard/SickBeard.py", line 416, in <module>
    main()
  File "SickBeard/SickBeard.py", line 329, in main
    sickbeard.CFG = ConfigObj(sickbeard.CONFIG_FILE)
  File "/home/osmc/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/home/osmc/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
lib.configobj.ConfigObjError: Parsing failed with several errors.
First error at line 200.`

I tried reinstalling python and configobj to no avail. Can anyone see whats going on?

Thanks

**Comment by VeNoMouS** [comment]
have you tried pip installing them?

**Comment by VeNoMouS** [comment]
Ok i'll try have a look into it for you, what version of python are you running 2, or 3?

**Comment by jappish84** [comment]
I think I installed 'configobj' successfully using pip, I saved the output:

```
osmc@Trdck:~/SickBeard$ pip install configobj
Collecting configobj
  Using cached https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
Collecting six (from configobj)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Building wheels for collected packages: configobj
  Running setup.py bdist_wheel for configobj ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-burGSM/configobj/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpN1vJF2pip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for configobj
  Running setup.py clean for configobj
Failed to build configobj
Installing collected packages: six, configobj
  Running setup.py install for configobj ... done
Successfully installed configobj-5.0.6 six-1.12.0
```

I was originally running python 2.7.13 then tried installing and running using python 3 but Python 3.5.3 only gives me a syntax error:

```osmc@Trdck:~$ python3 SickBeard/SickBeard.py 
  File "SickBeard/SickBeard.py", line 73
    except Exception, e:
                    ^
SyntaxError: invalid syntax```

**Comment by VeNoMouS** [comment]
sickbeard is not python 3 compatible

**Comment by VeNoMouS** [comment]
Try the following..

```
pip install wheel
```

then 

``` 
pip install --force-reinstall configobj
```

**Comment by jappish84** [comment]
Now the install looks better, but still the same issue:

```osmc@Trdck:~$ pip install wheel
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.32.3
osmc@Trdck:~$ pip install --force-reinstall configobj
Collecting configobj
  Using cached https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
Collecting six (from configobj)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Building wheels for collected packages: configobj
  Running setup.py bdist_wheel for configobj ... done
  Stored in directory: /home/osmc/.cache/pip/wheels/f1/e4/16/4981ca97c2d65106b49861e0b35e2660695be7219a2d351ee0
Successfully built configobj
Installing collected packages: six, configobj
Successfully installed configobj-5.0.6 six-1.12.0
osmc@Trdck:~$ python SickBeard/SickBeard.py 
Starting up Sick Beard torrentProviders
Traceback (most recent call last):
  File "SickBeard/SickBeard.py", line 416, in <module>
    main()
  File "SickBeard/SickBeard.py", line 329, in main
    sickbeard.CFG = ConfigObj(sickbeard.CONFIG_FILE)
  File "/home/osmc/SickBeard/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/home/osmc/SickBeard/lib/configobj.py", line 1302, in _load
    raise error
lib.configobj.ConfigObjError: Parsing failed with several errors.
First error at line 200.
osmc@Trdck:~$ ```

**Comment by VeNoMouS** [comment]
Have you checked your config.ini to make sure its not corrupt at all? ie around line 200..

**Comment by jappish84** [comment]
It must be something with the config.ini, just tried cloning another copy and running it without my config and it works fine

**Comment by VeNoMouS** [comment]
open it in an editor and check around line 200...

**Comment by jappish84** [comment]
It seems the file has been corrupted in many places, not just at line 200. I think I have an older backup laying around somewhere. Thanks for pointing me in the right direction

**Comment by VeNoMouS** [comment]
np

**Comment by jappish84** [comment]
It was corrupt from about line 195 and onward, corrected the lines using an older backup and now it's up and running again. Thanks again @VeNoMouS !
